### ISSUE TITLE
商品交易成功后评论商品上传图片报错。

### ISSUE THREAD

**Issue by lnk001** [baijiacms/baijiacmsV4#1]
![qq 20170103152035](https://cloud.githubusercontent.com/assets/17337394/21602561/217af0fc-d1d0-11e6-9bf6-a62928efca95.jpg)

**Comment by baijiacms** [comment]
我们测试过了，已经在用，没有发现此类问题。

**Comment by lnk001** [comment]
@baijiacms 请问晒图后上传的图片是放在哪个文件夹下， 不知道是不是文件夹没有写入权限。使用的是阿里云服务器 CentOS7.2 64位 | Nginx1.10 | PHP5.6

**Comment by baijiacms** [comment]
下个版本中修复您的问题。
